//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.1.1
//     from Assets/Scripts/Input System/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""Common Controls"",
            ""id"": ""019747f0-e0c6-47af-9cbe-0de1ff25020d"",
            ""actions"": [
                {
                    ""name"": ""Pan Mouse"",
                    ""type"": ""Value"",
                    ""id"": ""31387cf6-5189-4783-988c-45ecaf521bbe"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pan Keyboard"",
                    ""type"": ""Value"",
                    ""id"": ""a5bbbe9e-6789-4e48-9a28-ec2f4249e88d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Value"",
                    ""id"": ""37e04113-c019-4080-8403-841a95ecfc6d"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": ""Normalize(min=-1,max=1)"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""89d60ab7-ccae-4b1c-95fa-af8858f68381"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan Mouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""881bd941-8be4-4d14-9501-397f9ffce797"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": ""Normalize(min=-1,max=1)"",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""57e89b22-037d-41da-9d94-2a1e22c9f858"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan Keyboard"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a3d6d29b-3658-40d5-922e-c6d03ddd6c71"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan Keyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""be4b9a29-a17c-4361-a0a0-e6501179fa32"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan Keyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""e47c2f92-d430-4369-ab45-282b26466fff"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan Keyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""fd1c3b23-ad5e-4217-83e7-44c286e1546c"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan Keyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Unit Management"",
            ""id"": ""2588d7e9-7e12-4f1d-948b-347f16206ce9"",
            ""actions"": [
                {
                    ""name"": ""Interact"",
                    ""type"": ""Button"",
                    ""id"": ""e0580b16-29f3-412b-9e3a-f848dcb03a3f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""f2d0763f-8fa3-4705-9509-876c965f6385"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cursor"",
                    ""type"": ""Value"",
                    ""id"": ""52073590-efc7-4738-84a1-64248d626c79"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3038f30d-5a8e-41e1-b006-a9c49d316071"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fa07b537-809a-401b-a352-b5fd66a39ad1"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Interact"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9015d24c-e1ae-495d-a511-b0ca83564f2f"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Common Controls
        m_CommonControls = asset.FindActionMap("Common Controls", throwIfNotFound: true);
        m_CommonControls_PanMouse = m_CommonControls.FindAction("Pan Mouse", throwIfNotFound: true);
        m_CommonControls_PanKeyboard = m_CommonControls.FindAction("Pan Keyboard", throwIfNotFound: true);
        m_CommonControls_Zoom = m_CommonControls.FindAction("Zoom", throwIfNotFound: true);
        // Unit Management
        m_UnitManagement = asset.FindActionMap("Unit Management", throwIfNotFound: true);
        m_UnitManagement_Interact = m_UnitManagement.FindAction("Interact", throwIfNotFound: true);
        m_UnitManagement_Select = m_UnitManagement.FindAction("Select", throwIfNotFound: true);
        m_UnitManagement_Cursor = m_UnitManagement.FindAction("Cursor", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Common Controls
    private readonly InputActionMap m_CommonControls;
    private ICommonControlsActions m_CommonControlsActionsCallbackInterface;
    private readonly InputAction m_CommonControls_PanMouse;
    private readonly InputAction m_CommonControls_PanKeyboard;
    private readonly InputAction m_CommonControls_Zoom;
    public struct CommonControlsActions
    {
        private @PlayerControls m_Wrapper;
        public CommonControlsActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @PanMouse => m_Wrapper.m_CommonControls_PanMouse;
        public InputAction @PanKeyboard => m_Wrapper.m_CommonControls_PanKeyboard;
        public InputAction @Zoom => m_Wrapper.m_CommonControls_Zoom;
        public InputActionMap Get() { return m_Wrapper.m_CommonControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CommonControlsActions set) { return set.Get(); }
        public void SetCallbacks(ICommonControlsActions instance)
        {
            if (m_Wrapper.m_CommonControlsActionsCallbackInterface != null)
            {
                @PanMouse.started -= m_Wrapper.m_CommonControlsActionsCallbackInterface.OnPanMouse;
                @PanMouse.performed -= m_Wrapper.m_CommonControlsActionsCallbackInterface.OnPanMouse;
                @PanMouse.canceled -= m_Wrapper.m_CommonControlsActionsCallbackInterface.OnPanMouse;
                @PanKeyboard.started -= m_Wrapper.m_CommonControlsActionsCallbackInterface.OnPanKeyboard;
                @PanKeyboard.performed -= m_Wrapper.m_CommonControlsActionsCallbackInterface.OnPanKeyboard;
                @PanKeyboard.canceled -= m_Wrapper.m_CommonControlsActionsCallbackInterface.OnPanKeyboard;
                @Zoom.started -= m_Wrapper.m_CommonControlsActionsCallbackInterface.OnZoom;
                @Zoom.performed -= m_Wrapper.m_CommonControlsActionsCallbackInterface.OnZoom;
                @Zoom.canceled -= m_Wrapper.m_CommonControlsActionsCallbackInterface.OnZoom;
            }
            m_Wrapper.m_CommonControlsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @PanMouse.started += instance.OnPanMouse;
                @PanMouse.performed += instance.OnPanMouse;
                @PanMouse.canceled += instance.OnPanMouse;
                @PanKeyboard.started += instance.OnPanKeyboard;
                @PanKeyboard.performed += instance.OnPanKeyboard;
                @PanKeyboard.canceled += instance.OnPanKeyboard;
                @Zoom.started += instance.OnZoom;
                @Zoom.performed += instance.OnZoom;
                @Zoom.canceled += instance.OnZoom;
            }
        }
    }
    public CommonControlsActions @CommonControls => new CommonControlsActions(this);

    // Unit Management
    private readonly InputActionMap m_UnitManagement;
    private IUnitManagementActions m_UnitManagementActionsCallbackInterface;
    private readonly InputAction m_UnitManagement_Interact;
    private readonly InputAction m_UnitManagement_Select;
    private readonly InputAction m_UnitManagement_Cursor;
    public struct UnitManagementActions
    {
        private @PlayerControls m_Wrapper;
        public UnitManagementActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Interact => m_Wrapper.m_UnitManagement_Interact;
        public InputAction @Select => m_Wrapper.m_UnitManagement_Select;
        public InputAction @Cursor => m_Wrapper.m_UnitManagement_Cursor;
        public InputActionMap Get() { return m_Wrapper.m_UnitManagement; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UnitManagementActions set) { return set.Get(); }
        public void SetCallbacks(IUnitManagementActions instance)
        {
            if (m_Wrapper.m_UnitManagementActionsCallbackInterface != null)
            {
                @Interact.started -= m_Wrapper.m_UnitManagementActionsCallbackInterface.OnInteract;
                @Interact.performed -= m_Wrapper.m_UnitManagementActionsCallbackInterface.OnInteract;
                @Interact.canceled -= m_Wrapper.m_UnitManagementActionsCallbackInterface.OnInteract;
                @Select.started -= m_Wrapper.m_UnitManagementActionsCallbackInterface.OnSelect;
                @Select.performed -= m_Wrapper.m_UnitManagementActionsCallbackInterface.OnSelect;
                @Select.canceled -= m_Wrapper.m_UnitManagementActionsCallbackInterface.OnSelect;
                @Cursor.started -= m_Wrapper.m_UnitManagementActionsCallbackInterface.OnCursor;
                @Cursor.performed -= m_Wrapper.m_UnitManagementActionsCallbackInterface.OnCursor;
                @Cursor.canceled -= m_Wrapper.m_UnitManagementActionsCallbackInterface.OnCursor;
            }
            m_Wrapper.m_UnitManagementActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Interact.started += instance.OnInteract;
                @Interact.performed += instance.OnInteract;
                @Interact.canceled += instance.OnInteract;
                @Select.started += instance.OnSelect;
                @Select.performed += instance.OnSelect;
                @Select.canceled += instance.OnSelect;
                @Cursor.started += instance.OnCursor;
                @Cursor.performed += instance.OnCursor;
                @Cursor.canceled += instance.OnCursor;
            }
        }
    }
    public UnitManagementActions @UnitManagement => new UnitManagementActions(this);
    public interface ICommonControlsActions
    {
        void OnPanMouse(InputAction.CallbackContext context);
        void OnPanKeyboard(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
    }
    public interface IUnitManagementActions
    {
        void OnInteract(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
        void OnCursor(InputAction.CallbackContext context);
    }
}
